# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_client.ui'
#
# Created: Wed May  8 17:05:59 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AddClient(object):
    def setupUi(self, AddClient):
        AddClient.setObjectName("AddClient")
        AddClient.resize(695, 482)
        self.verticalLayout = QtGui.QVBoxLayout(AddClient)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(AddClient)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newButton = QtGui.QRadioButton(self.widget)
        self.newButton.setChecked(False)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout.addWidget(self.newButton)
        self.existingButton = QtGui.QRadioButton(self.widget)
        self.existingButton.setChecked(True)
        self.existingButton.setObjectName("existingButton")
        self.horizontalLayout.addWidget(self.existingButton)
        self.verticalLayout.addWidget(self.widget)
        self.clientLayout = QtGui.QHBoxLayout()
        self.clientLayout.setObjectName("clientLayout")
        self.newWidget = QtGui.QWidget(AddClient)
        self.newWidget.setObjectName("newWidget")
        self.formLayout = QtGui.QFormLayout(self.newWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.newWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.codeLineEdit = QtGui.QLineEdit(self.newWidget)
        self.codeLineEdit.setObjectName("codeLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.codeLineEdit)
        self.label_3 = QtGui.QLabel(self.newWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.cirifLineEdit = QtGui.QLineEdit(self.newWidget)
        self.cirifLineEdit.setObjectName("cirifLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cirifLineEdit)
        self.nameLineEdit = QtGui.QLineEdit(self.newWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_4 = QtGui.QLabel(self.newWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.newWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.saveAsFactoryBox = QtGui.QCheckBox(self.newWidget)
        self.saveAsFactoryBox.setObjectName("saveAsFactoryBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.saveAsFactoryBox)
        self.telLineEdit = QtGui.QLineEdit(self.newWidget)
        self.telLineEdit.setObjectName("telLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.telLineEdit)
        self.addressLineEdit = QtGui.QLineEdit(self.newWidget)
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.addressLineEdit)
        self.label_6 = QtGui.QLabel(self.newWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.clientLayout.addWidget(self.newWidget)
        self.line = QtGui.QFrame(AddClient)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.clientLayout.addWidget(self.line)
        self.existingWidget = QtGui.QWidget(AddClient)
        self.existingWidget.setObjectName("existingWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.existingWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clientButton = QtGui.QRadioButton(self.existingWidget)
        self.clientButton.setEnabled(False)
        self.clientButton.setChecked(True)
        self.clientButton.setObjectName("clientButton")
        self.horizontalLayout_4.addWidget(self.clientButton)
        self.factoryButton = QtGui.QRadioButton(self.existingWidget)
        self.factoryButton.setEnabled(False)
        self.factoryButton.setObjectName("factoryButton")
        self.horizontalLayout_4.addWidget(self.factoryButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.existingWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.filterLineEdit = QtGui.QLineEdit(self.existingWidget)
        self.filterLineEdit.setObjectName("filterLineEdit")
        self.horizontalLayout_2.addWidget(self.filterLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.clientsTableView = QtGui.QTableView(self.existingWidget)
        self.clientsTableView.setAlternatingRowColors(True)
        self.clientsTableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.clientsTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.clientsTableView.setObjectName("clientsTableView")
        self.clientsTableView.horizontalHeader().setHighlightSections(False)
        self.clientsTableView.horizontalHeader().setStretchLastSection(True)
        self.clientsTableView.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.clientsTableView)
        self.clientLayout.addWidget(self.existingWidget)
        self.verticalLayout.addLayout(self.clientLayout)
        self.buttonsLayout = QtGui.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.addButton = QtGui.QPushButton(AddClient)
        self.addButton.setObjectName("addButton")
        self.buttonsLayout.addWidget(self.addButton)
        self.cancelButton = QtGui.QPushButton(AddClient)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(AddClient)
        QtCore.QMetaObject.connectSlotsByName(AddClient)
        AddClient.setTabOrder(self.newButton, self.existingButton)
        AddClient.setTabOrder(self.existingButton, self.codeLineEdit)
        AddClient.setTabOrder(self.codeLineEdit, self.cirifLineEdit)
        AddClient.setTabOrder(self.cirifLineEdit, self.nameLineEdit)
        AddClient.setTabOrder(self.nameLineEdit, self.telLineEdit)
        AddClient.setTabOrder(self.telLineEdit, self.addressLineEdit)
        AddClient.setTabOrder(self.addressLineEdit, self.saveAsFactoryBox)
        AddClient.setTabOrder(self.saveAsFactoryBox, self.clientButton)
        AddClient.setTabOrder(self.clientButton, self.factoryButton)
        AddClient.setTabOrder(self.factoryButton, self.filterLineEdit)
        AddClient.setTabOrder(self.filterLineEdit, self.clientsTableView)
        AddClient.setTabOrder(self.clientsTableView, self.addButton)
        AddClient.setTabOrder(self.addButton, self.cancelButton)

    def retranslateUi(self, AddClient):
        AddClient.setWindowTitle(QtGui.QApplication.translate("AddClient", "Agregar cliente/fábrica", None, QtGui.QApplication.UnicodeUTF8))
        self.newButton.setText(QtGui.QApplication.translate("AddClient", "Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.existingButton.setText(QtGui.QApplication.translate("AddClient", "Existente", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AddClient", "Código", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AddClient", "CI/RIF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AddClient", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AddClient", "Tel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsFactoryBox.setText(QtGui.QApplication.translate("AddClient", "Fábrica", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AddClient", "Dirección", None, QtGui.QApplication.UnicodeUTF8))
        self.clientButton.setText(QtGui.QApplication.translate("AddClient", "Cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.factoryButton.setText(QtGui.QApplication.translate("AddClient", "Fábrica", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AddClient", "Filtrar", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("AddClient", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("AddClient", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))

